version: '3.8'
services:
  flask-server:
    build: ./flask-server
    ports:
      - "4567:4567"
    volumes:
      - ./flask-server:/flask-server
  frontend-react-js:
    build: ./react-client
    ports:
      - "3001:3001"
    volumes:
      - ./react-client:/react-client
networks:
  default:
    name: my-app-network