version: '3.8'
services:
  flask-server:
    build: ./flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./flask-server:/flask-server
  frontend-react-js:
    build: ./react-client
    ports:
      - "3000:3000"
    volumes:
      - ./react-client:/react-client
networks:
  default:
    name: my-app-network